### ISSUE TITLE
Move transfer config settings out of config.ini

### ISSUE THREAD

**Issue by JPWerling** [genomic-medicine-sweden/NGPIris#17]
**What needs to be done:**
Remove config.ini and apply default settings to transfer config in HCPManager.

**Suggestions on how to get it done:**
Remove config.ini and move settings into HCPManager. Function calculating sha256 needs to know these values however. These could go into  file called "definitions.py" or alike.

**What are the arguments for getting it done:**
Issues with reading the config.ini when installing to conda env. Configparser might also present issues if parent package also uses configparser.
`configparser.NoSectionError: No section: 'hcp'` after fresh install.

**Task is considered finished when:**
config.ini is no longer relied upon and HCPManager.upload_file() and calculate_etag() function as normal.

**Comment by JPWerling** [comment]
Following fresh conda environment creation with HCPInterface install:

In `test.py`
```
from HCPInterface.hcp import HCPManager

hcpm = HCPManager(<credentials>)
```

Running `python test.py`

```Traceback (most recent call last):
  File "test.py", line 3, in <module>
    hcpm = HCPManager('<redacted>', 'ngs-test')
  File "/home/xpjens/.conda/envs/temp_jens_38/lib/python3.8/site-packages/HCPInterface/hcp/hcp.py", line 134, in __init__
    self.transfer_config = TransferConfig(multipart_threshold=config.getint('hcp', 'size_threshold'),
  File "/home/xpjens/.conda/envs/temp_jens_38/lib/python3.8/configparser.py", line 818, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
  File "/home/xpjens/.conda/envs/temp_jens_38/lib/python3.8/configparser.py", line 808, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "/home/xpjens/.conda/envs/temp_jens_38/lib/python3.8/configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
  File "/home/xpjens/.conda/envs/temp_jens_38/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/home/xpjens/.conda/envs/temp_jens_38/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'hcp'
```
