### ISSUE TITLE
errror creating HCPmanager instance

### ISSUE THREAD

**Issue by parlar** [genomic-medicine-sweden/NGPIris#18]
Cannot establish a hcpmanager connection. Error msg below (removed/modified all credentials for security reasons):

PyDev console: starting.
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
from HCPInterface.hcp import HCPManager
endpoint = "https://vgtn0xxxx43"
aws_access_key_id = "xxxx"
aws_secret_access_key = "xxxx"
hcpm = HCPManager(endpoint, aws_access_key_id, aws_secret_access_key)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\PELA09\PycharmProjects\GMS-uploader\venv\lib\site-packages\HCPInterface\hcp\hcp.py", line 134, in __init__
    self.transfer_config = TransferConfig(multipart_threshold=config.getint('hcp', 'size_threshold'),
  File "C:\Users\PELA09\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 818, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
  File "C:\Users\PELA09\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 808, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "C:\Users\PELA09\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
  File "C:\Users\PELA09\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "C:\Users\PELA09\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'hcp'

**Comment by parlar** [comment]
tried using the cli, same result (removed path to credentials json for security reasons):


> hcpi -b umea -c <json_path> upload -i .\LICENSE -d /tmp/test

[2021-09-27 12:26:06,229] - DEBUG: Credentials file successfully utilized

Traceback (most recent call last):
  File "C:\Users\PELA09\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\PELA09\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\PELA09\PycharmProjects\GMS-uploader\venv\Scripts\hcpi.exe\__main__.py", line 7, in <module>
  File "c:\users\pela09\pycharmprojects\gms-uploader\venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\pela09\pycharmprojects\gms-uploader\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\pela09\pycharmprojects\gms-uploader\venv\lib\site-packages\click\core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "c:\users\pela09\pycharmprojects\gms-uploader\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\pela09\pycharmprojects\gms-uploader\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\pela09\pycharmprojects\gms-uploader\venv\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\pela09\pycharmprojects\gms-uploader\venv\lib\site-packages\HCPInterface\cli\base.py", line 26, in root
    hcpm = HCPManager(endpoint, access_key_id, access_key, bucket=bucket,credentials_path=credentials)
  File "c:\users\pela09\pycharmprojects\gms-uploader\venv\lib\site-packages\HCPInterface\hcp\hcp.py", line 134, in __init__
    self.transfer_config = TransferConfig(multipart_threshold=config.getint('hcp', 'size_threshold'),
  File "C:\Users\PELA09\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 818, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
  File "C:\Users\PELA09\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 808, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "C:\Users\PELA09\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
  File "C:\Users\PELA09\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "C:\Users\PELA09\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'hcp'

**Comment by parlar** [comment]
Could it be a connectivity issue? I've forwarded a question to our IT-dept about sjunet, if they need to open access.

If it is indeed a connectivity problem, perhaps it would be possible to raise an exception with a descriptive msg?

**Comment by sylvinite** [comment]
Duplicate of #17
