### ISSUE TITLE
no hcp section ... 

### ISSUE THREAD

**Issue by parlar** [genomic-medicine-sweden/NGPIris#19]
Still having issues with creating an hcpm instance.

running: 

```python
HCPInterface.hcp import HCPManager

hcpm = HCPManager(credentials_path="<path>/hcp.json")
```

Still getting this error:

[2021-09-28 08:52:04,561] - DEBUG: Credentials file successfully utilized
Traceback (most recent call last):
  File "C:/Users/PELA09/PycharmProjects/GMS-uploader/s3_test.py", line 3, in <module>
    hcpm = HCPManager(credentials_path="G:/Genetik/Mjukvaror/gms-uploader/hcp.json")
  File "C:\Users\PELA09\PycharmProjects\GMS-uploader\venv\lib\site-packages\HCPInterface\hcp\hcp.py", line 138, in __init__
    self.transfer_config = TransferConfig(multipart_threshold=config.getint('hcp', 'size_threshold'),
  File "C:\Users\PELA09\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 818, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
  File "C:\Users\PELA09\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 808, in _get_conv
[]
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "C:\Users\PELA09\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
  File "C:\Users\PELA09\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "C:\Users\PELA09\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'hcp'

 It looks like the config object (when used in hcp.py) is empty: 

```python
print(config.sections())
```
returns []

**Comment by sylvinite** [comment]
Resolved
